### ISSUE TITLE
Update to latest rust syntax

### ISSUE THREAD

**Issue by creationix** [swgillespie/rust-lisp#2]
I'm trying to learn how to write interpreters in rust.  If you have time, I would really appreciate it if this code compiled on rust 1.6.

Currently I get

```
   Compiling rust-lisp v0.0.1 (file:///Users/tim8019/Code/rust-lisp)
src/interpreter.rs:525:21: 525:26 error: `macro` is a reserved keyword
src/interpreter.rs:525                 let macro = Rc::new(Func(Macro(params, Rc::new(*body.clone()))));
                                           ^~~~~
Could not compile `rust-lisp`.
```

Thanks.

**Comment by creationix** [comment]
After renaming the `macro` variable, I get a new error.  I don't know enough rust syntax history to know what is meant here.

```
src/interpreter.rs:534:57: 534:58 error: expected type, found `|`
src/interpreter.rs:534     fn sexp_map(&mut self, params: &reader::Sexp, func: |&mut Interpreter, &reader::Sexp| -> EvalResult) -> Result<Vec<Rc<LispValue>>, String> {
```

**Comment by swgillespie** [comment]
@creationix Unfortunately, this is pretty ancient Rust. The problem here is that the type of func is |&mut Interpreter, &reader::Sexp| -> EvalResult, which at the time I wrote this meant a lambda of two arguments. Rust has a different approach to closures today, so this function would be written something like this today:

```
fn sexp_map<F: Fn(&mut Interpreter, &reader::Sexp) -> EvalResult>(&mut self, params: &reader::Sexp, func: F) -> Result<Vec<Rc<LispValue>>, String>
```

There's likely to be a lot of issues trying to get this to compile, sorry! This code is really old and Rust has evolved a lot since then. I've also realized that there are a lot of problems with this implementation, namely 1) every lisp value is reference counted, which is problematic with cycles and 2) there are different types for runtime and read-time s-expressions, which is very un lisp-like. More power to you if you want to get this working again, though!

**Comment by swgillespie** [comment]
@creationix Also, if you're interested in interpreters, https://github.com/swgillespie/rjs might be more interesting - it compiles on 1.6 and somewhat works. It's very far from completion and has some fundamental problems and unfortunately I haven't had much time to work on it, but it's better than this interpreter.

**Comment by creationix** [comment]
Thanks for the tips.  I'm just researching current best practices in this area.  Your tips and explanation is very helpful.

**Comment by swgillespie** [comment]
@creationix Glad I could help!
